import type { Metadata } from "next";

import "./globals.css";

import localFont from 'next/font/local'

const myfont = localFont({
  src: [
    {
      path: 'fonts/GeneralSans-Medium.woff',
      weight: '500',
      style: 'medium',
    },
    {
      path: 'fonts/GeneralSans-Semibold.woff',
      weight: '600',
      style: 'semibold',
    },
  
  ],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myfont.className}>{children}</body>
    </html>
  );
}
